### PR TITLE
Document min height

### PR DESCRIPTION
**Pull request by i-like-robots**
Table layout so that the footer will be positioned at the bottom of the viewport if the overall document size is less than the viewport height.

screen shot 2016-01-07 at 10 39 47

Tested behaviour when page is shorter than/taller than viewport in Chrome 46, Firefox 32, IE 11, iOS 8, iOS 9, BB10, Android 5 stock, Dolphin 11.4 and Opera mobile 34.

### CODE REVIEW

**Comment by wheresrhys** [comment]
We tried this a while ago. It broke galleries. Can't remember the exact reason, but in the analysis it seemed like it might end up affecting other things too from time to time, so ditched this approach

**Comment by i-like-robots** [comment]
I've taken a look at history (https://github.com/Financial-Times/next-sass-setup/pull/35 and https://github.com/Financial-Times/next-sass-setup/pull/39) and I've not been able to re-create 'treacle' scrolling on iOS 8 or 9 with or without galleries.

My hunch is that sluggish scrolling may have been related to the broken viewport units implementation shipped in iOS 8. The fundamental problem being that these values would have been continually recalculated which causes chaos when the browser chrome is shown/hidden on scroll. Some code underlying could have been the culprit, especially with the wobbly flexbox implementation!

**Comment by wheresrhys** [comment]
galleries breakage was a different thing - the layout properly broke

**Comment by i-like-robots** [comment]
Hmm, that doesn't seem to be a problem this time - at least not with the devices/browsers I've tested. Not much, if any, code from April still exists in the article app though so we may have unwittingly fixed the problem anyway!

**Comment by i-like-robots** [comment]
Since I'm on bug duty this week I'm happy to punt this and take the flak 😰

**Pull request merged**
