### PR TITLE
Catch rejected FontFaceObserver promise

### PR DESCRIPTION
**Pull request by lc512k**
@i-like-robots, works on bad 2G

### CODE REVIEW

**Comment by i-like-robots** [comment]
The timeout isn't really the problem (I think that's OK, maybe others don't!) but the error is not being caught, breaking everything else.

**Comment by lc512k** [comment]
@i-like-robots Timeout is back at 3sec, but we catch the rejected promise (x3), and `console.warn` the timeout message instead.

**Comment by matthew-andrews** [comment]
do we need to check if console is defined — this'll get run before polyfills are i believe…

**Comment by matthew-andrews** [comment]
hmm, i'm not sure about this.  promise chains without `catch`s won't break anything else — the default behaviour is for those errors to be swallowed..  something else may be broken here?

**Comment by i-like-robots** [comment]
This is one of the first bits of JS on the page, pre any Sentry or other scripts.

**Comment by lc512k** [comment]
moved to https://github.com/Financial-Times/n-layout/pull/69

**Pull request closed without merging**
