### PR TITLE
Restore zoom level on device orientation change

### PR DESCRIPTION
**Pull request by charypar**
Would be good to test this on more devices than just iOS, but I currently don't have any available.

### CODE REVIEW

**Comment by i-like-robots** [comment]
Haven't tested this but it seems risky because the viewport size isn't implicit. I personally think going belt and braces is always better.

**Comment by kaelig** [comment]
Have you tried with this instead?

```css
html {
  -webkit-text-size-adjust: 100%;
  text-size-adjust: 100%
}

**Comment by charypar** [comment]
@kaelig haven't, I will now.

**Comment by charypar** [comment]
Eh, I actually can't reproduce the problem any more... Strange.

**Comment by charypar** [comment]
Ok, never mind, it only happens on iOS 6 and none of the attempts to fix it work, so I'm closing this.

**Pull request closed without merging**
